export enum SSECause {
  REPUTATION_ALTERATION = 'REPUTATION_ALTERATION',
  RESERVATION_REQUEST = 'RESERVATION_REQUEST',
  RESERVATION_CONFIRMATION = 'RESERVATION_CONFIRMATION',
  RESERVATION_WITHDRAWAL = 'RESERVATION_WITHDRAWAL',
  COMPLAINT_SUBMISSION = 'COMPLAINT_SUBMISSION',
  COUNTER_COMPLAINT_SUBMISSION = 'COUNTER_COMPLAINT_SUBMISSION',
  PROHIBITION_DETERMINATION = 'PROHIBITION_DETERMINATION',
  PROHIBITION_TIMEFRAME_UPDATE = 'PROHIBITION_TIMEFRAME_UPDATE',
  PROHIBITION_CONCLUSION = 'PROHIBITION_CONCLUSION',
}
